spring.application.name=rna-analyzer
# MySQL database connection properties
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:cag}
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:mysql}:3306/${MYSQL_DB:cag}
spring.datasource.username=${MYSQL_USER:dev}
spring.datasource.password=${MYSQL_PASSWORD:cagdevkey}
# spring.datasource.url=jdbc:mysql://localhost:3306/cag
# spring.datasource.username=dev
# spring.datasource.password=cagkey
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT properties
security.jwt.secret-key=bX@9!zP#3L$d8V0gQpU^&7CkA%Nh6rT2*W_JxZx+F#0v~mY3E
security.jwt.issuer=Accounts API